version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    requirements-file: "Pipfile"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    requirements-file: "Pipfile.lock"